name: Eleventy Build
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Deps
        env:
          NODE_ENV: production
          HOSTING_SERVICE: biowebblog
        run: |
          npm i --fund false
      - name: Build
        env:
          NODE_ENV: production
          HOSTING_SERVICE: biowebblog
        run: |
          npm run prepare-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs
          publish_branch: bioweb-blog
          github_token: ${{ secrets.GITHUB_TOKEN }}
